### ISSUE TITLE
List: improving texts

### ISSUE THREAD

**Issue by silmiras** [teamsquad-io/amateur-tv#17]
We need improvements with the text that can appear on each pill from the list of cams:

- [x] padding from borders: the text should be little separated from borders, like 2 or 3 px
- [x] the texts should have one of those styles: regular / bold / italic / italic bold
- [x] being able to add a shadow or no (or border) something that will make easier to read on similar color behind if its marked

**Comment by contactashish13** [comment]
@silmiras I just debugged on your site and typography works properly. I have attached a video:

https://watch.screencastify.com/v/sJZuXfZXALalrIagfOLF

Let me know in case I'm misunderstanding this.

**Comment by contactashish13** [comment]
@silmiras did you get a chance to review this? Let me know in case you have any feedback

**Comment by contactashish13** [comment]
WP has some inbuilt core options for the color of texts. I will explore using those instead of custom color settings.

**Comment by silmiras** [comment]
@contactashish13 thinks I would like to improve:
![less_options](https://user-images.githubusercontent.com/123000179/221216583-268cf746-0bea-423e-9210-ec6a35b220fa.png)
![regular_but_italic](https://user-images.githubusercontent.com/123000179/221216585-5eaa3d09-78be-48a6-a5ae-2754f60bac95.png)

- I've selected regular and the text is still showing italic
- there are a lot of options for text appearance and I would like to simplify it on these 4: regular, italic, bold, italic bold
- the shadow, could it be allowing transparency, rounded corners and just covering the text?

**Comment by silmiras** [comment]
![shadow_options](https://user-images.githubusercontent.com/123000179/221217062-664de4d0-e8af-4995-a4a5-8cd15fa4b504.png)

**Comment by contactashish13** [comment]
@silmiras I have removed the font weight options - that then leaves you with only the styling as **bold** is not a style but a weight

![image](https://user-images.githubusercontent.com/12953439/223921051-957c5f0b-1b6f-47dd-9869-a4f98564e140.png)

![image](https://user-images.githubusercontent.com/12953439/223921142-33fa4703-4d90-48aa-a15a-0e93d2b9eb10.png)


I have also added the option for text shadow, which will affect all labels:

![image](https://user-images.githubusercontent.com/12953439/223921310-82e42df1-9b8e-498e-aed0-2679ca879d3b.png)

I want to discuss the rounded labels with you on the call as they look odd when all labels show up.

**Comment by contactashish13** [comment]
@javiercasares I'm not sure this should have been merged as @silmiras still hadn't tested this

**Comment by contactashish13** [comment]
From the meeting: background label required only for username and topic, with rounded borders (radius 25px) and increased spacing (padding 4px). Add some predefined colours to the background label
