### ISSUE TITLE
LiveCam: choosing cam

### ISSUE THREAD

**Issue by silmiras** [teamsquad-io/amateur-tv#19]
We need to be able to set the cam that will be displayed:

- [x] with affiliate code aded on the plugin has to be added to the iframe src: &a=[thecodefromtheplugin]
- [x] option for the most converting one with the filters we already have (gender+age)
- [x] option for specific cam adding on the parameters for the endpoint: https://www.amateur.tv/freecam/embed?lazyloadvideo=1&a_mute=1&livecam=liberalesmadrid
- [x] accepting a variable on the WP url that will be passed to the plugin block (I don't know how this is done or even if its possible, but i want something like https://blog.amateurdev.net/cam/liberalesmadrid or https://blog.amateurdev.net/mypage?livecam=liberalesmadrid

**Comment by contactashish13** [comment]
@silmiras It looks like the iframe does not support the genre and age parameters. I tried `https://www.amateur.tv/freecam/embed?width=890&height=580&lazyloadvideo=1&a_mute=1&genre=M&age=18-22` and it shows me a random couple video. Can you please let me know if the parameters being used are wrong?

**Comment by silmiras** [comment]
@contactashish13 it seems that is not released yet, thanks for letting me know. Just leave it ready for when they finish it on the platform.

**Comment by contactashish13** [comment]
@silmiras the changes are ready for review in https://github.com/teamsquad-io/amateur-tv/tree/issue-19

**Comment by contactashish13** [comment]
@silmiras 

> option for specific cam adding on the parameters for the endpoint: https://www.amateur.tv/freecam/embed?lazyloadvideo=1&a_mute=1&livecam=liberalesmadrid

The user may not know which cam to choose here as they are not aware of the list. Maybe there should be a way for the user to see a list of these cams (maybe a drop down instead of a text box) and then select the correct one?

**Comment by silmiras** [comment]
@contactashish13 when a WP editor need to add a specific cam, usually is like a model with her own blog and she wants to add her cam, in these kind of situations they know which camname they are going to use.
For the option "Camname Parameter" what I want is as in my example:

1. On my Front Page I've set up a camlist block with link including camname parameter
2. I click to "KattyLogan"
3. 4. That link should lead me to my second page named "Cam" that should get the parameter from the url and use it in the iframe to show "KattyLogan" live cam iframe. https://blog.amateurdev.net/cam/KattyLogan
![cam_list_link_go_to_cam_page](https://user-images.githubusercontent.com/123000179/222040632-e138a9de-bcd8-47d3-9a62-e36a63a44c4d.png)

--> I just don't know how to make it work.

**Comment by contactashish13** [comment]
@silmiras we can discuss the implementation and my changes on a call as it will be easier to show them there. I'm of course assuming that you are able to test different versions of the plugin directly from git.

**Comment by contactashish13** [comment]
@silmiras the help text has been added to the cam type dropdown:

![image](https://user-images.githubusercontent.com/12953439/222653798-babc70e7-6221-498b-8ddb-7bd9ba6867ba.png)
