### ISSUE TITLE
Fix problems in merge of #17, #18, #19

### ISSUE THREAD

**Issue by contactashish13** [teamsquad-io/amateur-tv#31]
I am creating a consolidated issue to make sure all changes have been merged properly. 

I would request @javiercasares to reach out to me in case of any doubts in merging in the future; CC @silmiras

**Comment by javiercasares** [comment]
I won't be approving PR's or other things. I'll send some commits to patch security issues, but @silmiras will be who approved PRs.

Moreover, as a reminder, if a PR is not for approval yet, it is better to create it as a Draft Mode. All PRs may be approved as they are PRs.

**Comment by contactashish13** [comment]
@silmiras this also fixes issue you had highlighted in https://github.com/teamsquad-io/amateur-tv/issues/17#issuecomment-1443838334 where the font style did not change from italics. I have updated the plugin on the test site and tested it there. You may need to clear your browser cache for the changes to take effect.
