### ISSUE TITLE
Github process - issues, branches, PRs and releases

### ISSUE THREAD

**Issue by contactashish13** [teamsquad-io/amateur-tv#32]
@javiercasares From what I have understood, please confirm if this is the Github process you prefer:

- @silmiras will create issues and assign them to me
- once it is ready for testing I will inform @silmiras without creating a PR. She will test it on the branch
- once she approves I will create a PR and assign it to you
- you will merge 

I'm not sure of the process after this up to the release so it would be great if you could share your thoughts on this

**Comment by javiercasares** [comment]
- Silvia will create the issues and assign to whoever needs to extend them.
- When an Issue is ready, and “ready to be tested” it can be created as a PR draft. So, it's a PR, but not to merge. It should have everything to be, but can be changed with new commits.
- When the PR is ready, you can change it from Draft to Ready.
- At that moment, any PR can be reviewed by anybody and approved it (merge in main).

Thereafter, before creating a release, an Issue to update things like “versions” or whatever can be made and be merged in main, and then, create a release.

On my side, I'll be as a developer as well, but only for code review, testing or preparing new releases.
