### ISSUE TITLE
Test with WordPress6.2

### ISSUE THREAD

**Issue by contactashish13** [teamsquad-io/amateur-tv#37]
WordPress 6.2 is imminent in the end of march so it would be good to test this and update the readme.txt accordingly.

@javiercasares Let me know if this testing comes under your purview or I should tackle this

CC @silmiras

**Comment by javiercasares** [comment]
Yes, I'll check that next week, but everything I tried from 6.1 to 6.2 is working fine.

**Comment by silmiras** [comment]
@contactashish13 we need the plugin for testing versions on our test WP

**Comment by javiercasares** [comment]
Looks that works fine.
